### ISSUE TITLE
organize sub-directories

### ISSUE THREAD

**Issue by codetricity** [theta360developers/theta-javascript#1]
top-level

* fake-theta
* real-theta
* x - specific to x, like cameraControlSource
* sc2
* z1

Organize scripts into the same sub-directory system as the API documentation

https://github.com/ricohapi/theta-api-specs/tree/main/theta-web-api-v2.1

if the file is blank, do something like

```
// TODO: erik 
```
The folders under fake-theta and real-theta should be:

* commands
* options
* protocols
* examples

Under protocols:

* protocols
  * info.js
  * state.js

under commands:

* commands
  * listFiles.js
  * takePicture.js
  * getLivePreview.js

under options

* options
  * getOptions.js  - put a good set of options here
  * setOffDelay.disable.js
  * setOffDelay.enable.js - set to default value
  * sleepDelay.disable.js
  * sleepDelay.enable.js - set to default value
  * videoStitching.js
  * captureMode.image.js
  * captureMode.video.js

* examples
  * downloadImage.js - with known URL hardcoded 
  * downloadLastImage.js

**Comment by codetricity** [comment]
@jcasman in the recent push you did directly to main, change the filenames for getlivepreviewfake.js to `getLivePreview.js` per the command spelling is the official API documentation

**Comment by jcasman** [comment]
Added X, Z1 and SC2 specific dirs. Closing issue.

**Comment by codetricity** [comment]
either use the file name convention proposed here or suggest a different file name convention.

**Comment by codetricity** [comment]
https://github.com/theta360developers/theta-javascript/pull/11
