### ISSUE TITLE
videoStitching Trouble Getting it to Work- Unrelated to Forum Post 

### ISSUE THREAD

**Issue by AirTechWick** [theta360developers/theta-javascript#13]
I'm using [Docs](https://github.com/ricohapi/theta-api-specs/blob/main/theta-web-api-v2.1/options/video_stitching.md) and I am getting an Error.
![image](https://github.com/theta360developers/theta-javascript/assets/82003999/5a1ca7aa-1c70-4b41-8730-7be03bdcfefb)

**Comment by codetricity** [comment]
Do you have the camera in video mode? videoStitching cannot be set if the camera is in image mode

**Comment by AirTechWick** [comment]
This worked! Thank you.
