### ISSUE TITLE
Handling the data that is returned from API

### ISSUE THREAD

**Issue by AirTechWick** [theta360developers/theta-javascript#7]
In JavaScript we have to specify how we want the data to be returned to us. I think insomnia handles the returned data usually.

![image](https://github.com/theta360developers/theta-javascript/assets/82003999/3ed6d3b5-6dd0-4a23-9cfb-571220e213b9)

In another command live preview we handled returning the data

![image](https://github.com/theta360developers/theta-javascript/assets/82003999/5569b065-88a3-43a6-8d91-eb9e774e0571)

If their is any future commands that need's different handling of data then I'll bring it up to you guys.

**Comment by AirTechWick** [comment]
Will follow [theta-web-api-v2.1](https://github.com/ricohapi/theta-api-specs/tree/aa138ed72aafac3af4262220c46344c3c5b60656/theta-web-api-v2.1) Docs to have the same outputs/results

**Comment by jcasman** [comment]
This is useful. Interesting that Insomnia might handle this itself. I'm closing this issue.
